

import getpass
import os
from langchain.tools import Tool
from langgraph.graph import StateGraph, END
from langchain_core.runnables import RunnableLambda
from langchain_openai import ChatOpenAI
from langsmith import traceable
from langserve import RemoteRunnable, add_routes
from github import Github
import subprocess
from fastapi import FastAPI
from dotenv import load_dotenv
from datetime import datetime
from langchain.tools import tool

load_dotenv()  # Loads from .env by default
token = os.getenv("GITHUB_TOKEN")
repo_name = os.getenv("GITHUB_REPO")
g = Github(token)


def _set_env(var: str):
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"{var}: ")


_set_env("OPENAI_API_KEY")




# --- Define the state structure ---
class AgentState(dict):
    prompt: str
    validate_result: str
    validation_passed: bool
    scan_result: str
    scan_passed: bool
    repo_url: str


# --- LLM Setup ---
llm = ChatOpenAI(model="gpt-4o", temperature=.7, max_retries=5)

# --- LangChain Tools with LangSmith Tracing ---
@traceable(name="generate_terraform")
def terraform_generator(prompt: str) -> str:
    response =  llm.invoke(f"Generate secure Terraform code for: {prompt}")

    print(response)
    return response.content

@traceable(name="validate_terraform")
def terraform_validator(_: str = "") -> str:
    try:
        result = subprocess.run(
            ["terraform", "init"],
            check=True,
            capture_output=True,
            text=True  # so output is string, not bytes
        )
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Terraform init failed!")
        print("Return code:", e.returncode)
        print("STDOUT:", e.stdout)
        print("STDERR:", e.stderr)    
    fmt = subprocess.run(["terraform", "fmt", "-check"], capture_output=True, text=True)
    validate = subprocess.run(["terraform", "validate"], capture_output=True, text=True)
    return fmt.stdout + "\n" + validate.stdout

@traceable(name="lint_terraform")
def terraform_linter(_: str = "") -> str:
    tflint = subprocess.run(["tflint"], capture_output=True, text=True)
    checkov = subprocess.run(["checkov", "-d", "."], capture_output=True, text=True)
    return tflint.stdout + "\n" + checkov.stdout

@traceable(name="create_pr")
def github_pr_creator(_: str = "") -> str:

    repo = g.get_repo(repo_name)
    branch_name = f"""terraform-update-{datetime.now().strftime("%Y-%m-%d-%H-%M-%s")}"""


    subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    subprocess.run(["git", "add", "main.tf"], check=True)
    subprocess.run(["git", "commit", "-m", "Add generated Terraform code"], check=True)
    subprocess.run(["git", "push", "origin", branch_name], check=True)

    pr = repo.create_pull(title="Terraform Infra Update", body="This PR was auto-generated by an AI agent.", head=branch_name, base="main")
    return pr.html_url


@tool
def read_github_repo(repo_url: str) -> dict:
    """
    Reads all files in a GitHub repo and returns a dictionary of file paths to file contents.
    Supports repos with Terraform, Markdown, and other files.
    """
    try:
        if "github.com" not in repo_url:
            raise ValueError("Invalid GitHub URL")

        parts = repo_url.rstrip("/").split("/")
        owner, repo_name = parts[-2], parts[-1]

        repo = g.get_repo(f"{owner}/{repo_name}")
        contents = repo.get_contents("")
        file_map = {}

        def fetch_files_recursively(items):
            for item in items:
                if item.type == "dir":
                    fetch_files_recursively(repo.get_contents(item.path))
                elif item.type == "file":
                    file_map[item.path] = item.decoded_content.decode(errors="ignore")

        fetch_files_recursively(contents)
        return file_map

    except Exception as e:
        return {"error": str(e)}
    

def summarize_file_purposes(file_map: dict) -> dict:
    """
    Takes a dictionary of file paths to contents and returns a summary
    of each file’s purpose using the LLM.
    """
    summaries = {}

    for path, content in file_map.items():
        # Skip empty or huge files
        if not content.strip():
            summaries[path] = "Empty file."
            continue

        # Truncate long content for performance (adjust as needed)
        truncated_content = content[:2000]

        prompt = (
            f"You are analyzing a codebase. Here is the content of a file:\n\n"
            f"Filename: {path}\n\n"
            f"```text\n{truncated_content}\n```\n\n"
            f"Please summarize the purpose of this file in 1-2 sentences."
        )

        try:
            response = llm.invoke([{"role": "user", "content": prompt}])
            summaries[path] = response.content.strip()
        except Exception as e:
            summaries[path] = f"Error summarizing: {str(e)}"

    return summaries

# --- LangChain Tool Wrappers ---
generate_tool = Tool(name="generate_terraform", func=terraform_generator, description="Generate Terraform code from prompt")
validate_tool = Tool(name="validate_terraform", func=terraform_validator, description="Validate and format Terraform")
lint_tool = Tool(name="lint_terraform", func=terraform_linter, description="Lint and scan Terraform code")
pr_tool = Tool(name="create_pr", func=github_pr_creator, description="Create GitHub PR")

# --- Tool Nodes ---
def generate_terraform_code(state: AgentState) -> AgentState:
    code = generate_tool.invoke(state["prompt"])
    with open("main.tf", "w") as f:
        f.write(code)
    state["terraform_code"] = code
    return state

def validate_terraform_code(state: AgentState) -> AgentState:
    result = validate_tool.invoke("")
    print(result)
    state["validate_result"] = result
    state["validation_passed"] = "Success!" in result
    return state

def scan_terraform_code(state: AgentState) -> AgentState:
    result = lint_tool.invoke("")
    state["scan_result"] = result
    state["scan_passed"] = "Passed checks" in result
    return state

def create_github_pr(state: AgentState) -> AgentState:
    pr_url = pr_tool.invoke("")
    state["pr_url"] = pr_url
    return state

# --- Decision Node ---
def check_if_passed(state: AgentState) -> str:
    if state["validation_passed"] and state["scan_passed"]:
        return "create_pr"
    return END

# --- Build LangGraph ---
graph = StateGraph(AgentState)
graph.add_node("summarize_codebase", RunnableLambda(read_github_repo))

graph.add_node("generate", RunnableLambda(generate_terraform_code))
graph.add_node("validate", RunnableLambda(validate_terraform_code))
graph.add_node("scan", RunnableLambda(scan_terraform_code))
graph.add_node("create_pr", RunnableLambda(create_github_pr))

graph.set_entry_point("generate")
graph.add_edge("generate", "validate")
graph.add_edge("validate", "scan")
graph.add_conditional_edges("scan", check_if_passed, {"create_pr": "create_pr", END: END})
graph.add_edge("create_pr", END)

workflow = graph.compile()

# --- LangServe API ---
app = FastAPI()
add_routes(app, workflow, path="/terraform-agent")

# --- CLI Runner ---
if __name__ == "__main__":
    initial_state = AgentState({
        "prompt": "Generate only valid Terraform HCL code to deploy a public S3 bucket in us-west-2. Do not include explanations or markdown formatting. Only output code without formatting hcl. Use checkov to ensure best practices are being met",
        "repoUrl": "https://github.com/seansabour/terraform_ai_agent"
    })
    final_state = workflow.invoke(initial_state)
    print("Final state:", final_state)
